<?php 
$title = 'Meus Álbum';
$this->headTitle($title); 
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a class="btn btn-success" href="<?php echo $this->url('album', array('action'=>'add'));?>">Adicionar Novo Álbum</a>
</p>

<table class="table">
<tr>
    <th>Titulo</th>
    <th>Artista</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($albums as $album) : ?>
<tr>
    <td><?php echo $this->escapeHtml($album->getTitle());?></td>
    <td><?php echo $this->escapeHtml($album->getArtist());?></td>
    <td>
        <a class="btn btn-mini" href="<?php echo $this->url('album',
            array('action'=>'edit', 'id' => $album->getId()));?>">Editar</a>
        <a class="btn btn-mini btn-danger" onclick="return confirm('Tem certeza que deseja deletar esse álbum?');" href="<?php echo $this->url('album',
            array('action'=>'delete', 'id' => $album->getId()));?>">Deletar</a>
        
        &nbsp;||&nbsp;
        
        <a class="btn btn-mini btn-info" href="<?php echo $this->url('album',
            array('action'=>'music', 'id' => $album->getId()));?>">Músicas</a>
        
    </td>
</tr>
<?php endforeach; ?>
</table>